config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'addresses#index'
  post '/signup', to: 'users#create'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :tours
  resources :addresses
  resources :booking_requests
  resources :ratings
  resources :comments
  resources :categories
  resources :likes
  resources :activities

  namespace :admin do
    resources :tours
    resources :users
    resources :booking_requests
    resources :addresses
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
  has_one_attached :picture
  has_many :tours
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking_request.rb
class BookingRequest < ApplicationRecord
  belongs_to :tour
  belongs_to :user

  scope :waiting, ->{where(status: nil)}
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tour
  belongs_to :user
  has_many :likes
  belongs_to :category
  belongs_to :parent,  class_name: "Comment", optional: true 
  has_many   :sub_comments, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
  scope :root_comments, -> {where parent_id: nil}
  validates :content, presence: true, allow_blank: false
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :tour
  belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_one_attached :picture
  belongs_to :address
  has_many :comments
  has_many :ratings
  has_many :booking_requests
  has_many :users, through: :booking_requests

  def self.search(name, page)
    if name	
      where('name LIKE ?', "%#{name}%").paginate(page: page)	
    else	
      paginate(page: page)	
    end	
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :booking_requests
  has_many :tours, through: :booking_requests
  has_many :comments
  has_many :likes
  has_many :liked_comments, through: :likes, source: :comment
  attr_accessor :remember_token
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, 
                    uniqueness: {case_sensitive: false}
  has_secure_password                                   
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? (remember_token)
  end
  def self.search(name, page)
    if name 
      where('name LIKE ?', "%#{name}%").paginate(page: page)  
    else  
      paginate(page: page)  
    end 
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses = Address.paginate(page: params[:page])
  end

  def show
    @address = Address.find(params[:id])
    @tours = @address.tours.paginate(page: params[:page])
  end

end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < ApplicationController
  before_action :require_admin
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  def index
    @addresses = Address.paginate(page: params[:page])
  end

  def show
    @tours = @address.tours.paginate(page: params[:page])
  end

  def new
    @address = Address.new
  end

  def edit
  end

  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to admin_address_path(@address)
      flash[:success] = "Successfully create"
    else
      flash[:danger] = "Error"
      render "new"
    end
  end

  def update
    if @address.update_attributes(address_params)
      flash[:success] = "Update address successfully"
      redirect_to admin_addresses_path
    else
      render "edit"
    end
  end

  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_address
    @address = Address.find(params[:id])
  end

  def require_admin
    unless current_user.admin?
      flash[:danger] = "You are not admin"
      redirect_to root_path
    end
  end

  def address_params
    params.require(:address).permit(:city, :picture)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new(like_params)
  end

  def create
    @like = current_user.likes.new(like_params)
    respond_to do |format|
      if @like.save
        format.html { redirect_to @like.comment.tour, notice: "like was successfully created." }
      else
        format.html { redirect_to @like.comment.tour, alert: @like.errors.full_messages.first}
      end
    end
  end

  def destroy
    @like = Like.find params[:id]
    comment = @like.comment
    respond_to do |format|
      if @like.destroy
        format.html { redirect_to comment.tour, notice: "unliked!"}
      end
    end
  end

  private
  def like_params
    params.require(:likes).permit(:user_id, :comment_id)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  def index
    @tours = Tour.search(params[:name], params[:page])
  end

  def show
    @tour = Tour.find(params[:id])
    @comments = @tour.comments.root_comments
    @booking_request = @tour.booking_requests.find_by(user_id: current_user.try(:id))
    @comment = @tour.comments.build( user_id: current_user.try(:id))
  end
  
  private
  def tour_params
    params.require(:tour).permit(:name, :price, :content)
  end

  def logged_in_user
    unless logged_in?
      respond_to do |format|
        format.html { redirect_to login_url, alert: 'Please log in.' }
      end
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
      
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/user_helper.rb
module UserHelper
 def gravatar_for(user,options = {size: 80})
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size  = options[:size]
  gravatar_url  = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/addresses/edit.html.erb
<% provide(:title, "Edit address") %>
<h1>Update City</h1>
<div class="row">
  <div  class="col-md-6 col-md-offset-3">
    <%= form_for([:admin, @address]) do |f| %>
      <%= render 'shared/error_messages', object: @address %>
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
  
      <%= f.label "Picture" %>
      <%= f.file_field :picture %>
      <br>
      <%= f.submit  "Save changes", class: "btn  btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/admin/addresses/index.html.erb
<% provide(:title,'All city') %>
<h1>All city</h1>
<%= will_paginate %>
<div class="container">
  <div class="row">
    <% @addresses.each do |address| %>
      <div class="nav-thumbnails">
        <div class="col-sm-3">
          <div class="item-thumbnail" title="Tour du lich tai <%= address.city %>">
            <%= link_to "Edit", edit_admin_address_path(address) %> ||
            <%= link_to "Delete", admin_address_path(address), method: :delete,data: { confirm: "You sure?" } %>
            <%= link_to admin_address_path(address) do %>
            <div>
                <% if address.picture.attached? %>
                  <%= image_tag(address.picture, size: "400x200") %>
                <% end %>
                <h4 class="item-name"><%= address.city%></h4> 
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= will_paginate %>

app/views/admin/addresses/new.html.erb
<% provide(:title, 'Create city') %>
<% provide(:button_text, 'Create address') %>
<h1>Create Address</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([:admin, @address]) do |f| %>
      <%= render 'shared/error_messages', object: @address %>
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
  
      <%= f.label "Picture" %>
      <%= f.file_field :picture %><br>
  
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/addresses/show.html.erb
<% provide(:title,'All tours') %>
<h1>All tours</h1>

<%= will_paginate @tours %>
<h2>Search Tour</h2>

<div class="nav-search">
  <div class="row">
    <div class="col-sm-6">
    </div>
    <div class="col-sm-3" class="input-group">
      <%= form_tag(tours_path, method: :get, class: "search-form", role: "search") do %>
      <%= text_field_tag :name, params[:name], placeholder: "Search Posts", class: "search-field search-input form-control searchbox"%>
      <%= button_tag("", type: "submit", class: "searchbutton btn-search fa fa-search") %>
      <% end %>
    </div>
  </div>
</div>
<ul class="addresses">
  <div class="row">
    <% @tours.each do |tour| %>
      <div class="col-sm-4">
        <div class="tours-layout">
          <div class="image-wrapper">
            <%= link_to(admin_tour_path(tour), class: "link") do %>
              <div>
                <% if tour.picture.attached? %>
                  <%= image_tag(tour.picture, size: "400x270") %>
                <% end %>
              </div>
            <% end %>
            <div class="title-wrapper">
              <%= link_to(tour.name, admin_tour_path(tour), class: "title") %>
            </div>
          </div>
          <div class="content-wrapper">
            <div class="content">
              <div class="title">
                <div class="price">
                  <span class="number"><%= tour.price %></span>
                  <sup>VND</sup>
                </div>
                <p class="for-price">3 ngay 2 dem</p>
              </div>
              <div class="group-btn-tours">
                <%= link_to("Xem", admin_tour_path(tour), class: "left-btn") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</ul>
<%= will_paginate @tours %>