config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'addresses#index'
  post '/signup', to: 'users#create'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :tours
  resources :addresses
  resources :booking_requests
  resources :ratings
  resources :comments
  resources :categories
  resources :likes
  resources :activities

  namespace :admin do
    resources :tours
    resources :users
    resources :booking_requests
    resources :addresses
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_one_attached :picture
  belongs_to :address
  has_many :comments
  has_many :ratings
  has_many :booking_requests
  has_many :users, through: :booking_requests

  def self.search(name, page)
    if name	
      where('name LIKE ?', "%#{name}%").paginate(page: page)	
    else	
      paginate(page: page)	
    end	
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  before_action :require_admin

  def index
    @tours = Tour.paginate(page: params[:page])
  end

  def new
    @tour = Tour.new
  end

  def show
    @tour = Tour.find(params[:id])
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      flash[:success] = "Create tour successfully"
    else
      flash[:danger] = "Create fail"
      render :new
    end
  end

  def update
    @tour = Tour.find(params[:id])
    if @tour.update_attributes(tour_params)
      flash[:success] = "Update tour successfully"
      redirect_to admin_address_path(@tour.address)
    else
      render "edit"
    end
  end

  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def require_admin
    unless current_user.admin?
      flash[:danger] = "You are not admin"
      redirect_to root_path
    end
  end

  def tour_params
    params.require(:tour).permit(:name, :price, :content, :picture)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  def index
    @tours = Tour.search(params[:name], params[:page])
  end

  def show
    @tour = Tour.find(params[:id])
    @comments = @tour.comments.root_comments
    @booking_request = @tour.booking_requests.find_by(user_id: current_user.try(:id))
    @comment = @tour.comments.build( user_id: current_user.try(:id))
  end
  
  private
  def tour_params
    params.require(:tour).permit(:name, :price, :content)
  end

  def logged_in_user
    unless logged_in?
      respond_to do |format|
        format.html { redirect_to login_url, alert: 'Please log in.' }
      end
    end
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/admin/tours/_form.html.erb
<%= form_for([:admin, @tour]) do |f| %>
  <%= render 'shared/error_messages', object: @tour %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  
  <%= f.label :price %>
  <%= f.text_field :price, class: 'form-control' %>
  
  <%= f.label :content %>
  <%= f.text_area(:content, size: "50x10", class: 'form-control') %>
  
  <%= f.label "Picture" %>
  <%= f.file_field :picture %><br>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %><% end %>
  

app/views/admin/tours/edit.html.erb
<% provide(:title, "Edit tour") %>
<h1>Update Tour</h1>
<div class="row">
  <div  class="col-md-6 col-md-offset-3">
    <%= form_for([:admin, @tour]) do |f| %>
      <%= render 'shared/error_messages', object: @tour %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
  
      <%= f.label "Picture" %>
      <%= f.file_field :picture %>
      <br>
      <%= f.submit  "Save changes", class: "btn  btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/admin/tours/index.html.erb
<% provide(:title,'All tours') %>
<h1>All tours</h1>

<%= will_paginate %>
<h2>Search Tour</h2>

<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-2">
    <%= form_tag(tours_path, method: :get) do %>
    <%= text_field_tag :name, params[:name] %>
  </div>
  <div class="col-sm-2">
    <%= submit_tag "Search"%>
  </div>

  <% end %>
</div>
<ul class="tours">
  <% @tours.each do |tour| %>
    <li>
     <%= link_to tour.name, admin_tour_path(tour), class: "col-md-2" %> 
     <%= link_to "Delete", admin_tour_path(tour), method: :delete,data: { confirm: "You sure?" } %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/admin/tours/new.html.erb
<% provide(:title, 'Create tours') %>
<% provide(:button_text, 'Create your tour') %>
<h1> Create tours </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/tours/show.html.erb
  <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour.name %>
  <br>
  <strong>Price:</strong>
  <%= @tour.price %>
  <br>
  <strong>Content:</strong>
  <%= @tour.content %>
  <br>
  <strong>Quanity user book this tour:</strong>
  <%= @tour.booking_requests.waiting.count %>
  <br>
  <%= link_to "Edit", edit_admin_tour_path(@tour) %>
  <%= link_to "Delete", admin_tour_path(@tour), method: :delete, data: { confirm: "You sure ?" } %>
</p>