config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'addresses#index'
  post '/signup', to: 'users#create'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :tours
  resources :addresses
  resources :booking_requests
  resources :ratings
  resources :comments
  resources :categories
  resources :likes
  resources :activities

  namespace :admin do
    resources :tours
    resources :users
    resources :booking_requests
    resources :addresses
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_one_attached :picture
  belongs_to :address
  has_many :comments
  has_many :ratings
  has_many :booking_requests
  has_many :users, through: :booking_requests

  def self.search(name, page)
    if name	
      where('name LIKE ?', "%#{name}%").paginate(page: page)	
    else	
      paginate(page: page)	
    end	
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  before_action :require_admin

  def index
    @tours = Tour.paginate(page: params[:page])
  end

  def new
    @tour = Tour.new
  end

  def show
    @tour = Tour.find(params[:id])
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      flash[:success] = "Create tour successfully"
    else
      flash[:danger] = "Create fail"
      render :new
    end
  end

  def update
    @tour = Tour.find(params[:id])
    if @tour.update_attributes(tour_params)
      flash[:success] = "Update tour successfully"
      redirect_to admin_address_path(@tour.address)
    else
      render "edit"
    end
  end

  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def require_admin
    unless current_user.admin?
      flash[:danger] = "You are not admin"
      redirect_to root_path
    end
  end

  def tour_params
    params.require(:tour).permit(:name, :price, :content, :picture)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  def index
    @tours = Tour.search(params[:name], params[:page])
  end

  def show
    @tour = Tour.find(params[:id])
    @comments = @tour.comments.root_comments
    @booking_request = @tour.booking_requests.find_by(user_id: current_user.try(:id))
    @comment = @tour.comments.build( user_id: current_user.try(:id))
  end
  
  private
  def tour_params
    params.require(:tour).permit(:name, :price, :content)
  end

  def logged_in_user
    unless logged_in?
      respond_to do |format|
        format.html { redirect_to login_url, alert: 'Please log in.' }
      end
    end
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/index.html.erb
<% provide(:title,'All tours') %>
<h1>All tours</h1>

<%= will_paginate %>
<h2>Search Tour</h2>

<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-2">
    <%= form_tag(tours_path, method: :get) do %>
    <%= text_field_tag :name, params[:name] %>
  </div>
  <div class="col-sm-2">
    <%= submit_tag "Search" %>
  </div>

  <% end %>
</div>
<ul class="tours">
  <% @tours.each do |tour| %>
    <li>
     <%= link_to tour.name, tour %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @tour.name %>
  <br>
  <strong>price:</strong>
  <%= @tour.price %>
  <br>
  <strong>content:</strong>
  <%= @tour.content %>
  <br>
  <strong>rate:</strong>
  <%= @tour.ratings.average(:quanity) %>
  <br>
  <strong>status:</strong>
  <% if @booking_request && @booking_request.status %>
    <p>booking_request approved</p>
  <% elsif @booking_request %>
    <p>booking_request rejected</p>
  <% else %>
  <%= link_to "book this tour", booking_requests_path(booking_request: {tour_id: @tour.id}), method: :post %>
   <% end %>
  <br>
</p>

<%= link_to 'Book Tour', booking_requests_path(booking_request:{tour_id: @tour.id}), method: :post %>
<% flash.each do |key, value| %>
    <div id="error_explanation">
      <div class="alert alert-#{key}">
        <%= value unless value.blank? %>
      </div>
    </div>
  <% end %>
<%=  @comment.errors.any? %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for(@comment) do |f| %>
    <%= f.label :comment %>
    <%= f.text_field :content, class: 'form-control' %>
    <%= f.hidden_field :tour_id, value: @tour.id %>
    <%= f.hidden_field :category_id, value: Category.first.id %>
    <%= f.submit %>
  <% end %>
  </div>
</div>

<% @comments.each do |comment| %>
  <%= comment.content %> on the user <%= comment.user.name %>
  <%= button_tag "Edit", id: "toggle_comment_#{comment.id}", class: "toggle_comment" %>
  <%= comment.likes.count %>
  <% if current_user.likes.find_by(comment_id: comment.id) %>
  <%= link_to "Unlike",like_path(current_user.likes.find_by(comment_id: comment.id)), method: :delete %>
  <% else %>
  <%= link_to "Like",likes_path(likes: {comment_id: comment.id}), method: :post %>
  <% end %>
  <%= form_for (comment), html: {style: 'display: none;'} do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :content, class: 'form-control' %>
   <%= f.submit %>
<% end %>

  <p> sub cmt</p>
    <% comment.sub_comments.each do |sub_cmt| %>
      <p><%= sub_cmt.content %> </p>
      <%= button_tag "Edit", id: "toggle_comment_#{sub_cmt.id}", class: "toggle_comment" %>
      <% if current_user.likes.find_by(comment_id: sub_cmt.id) %>
      <%= link_to "Unlike",like_path(current_user.likes.find_by(comment_id: sub_cmt.id)), method: :delete %>
      <% else %>
      <%= link_to "Like",likes_path(likes: {comment_id: sub_cmt.id}), method: :post %>
      <% end %>
      <%= sub_cmt.likes.count %>
      <%= form_for (sub_cmt), html: {style: 'display: none;'} do |f| %>
      <%= f.label :comment %>
      <%= f.text_field :content, class: 'form-control' %>
      <%= f.submit %>
    <% end %>
  <% end %>

  <%= form_for (Comment.new) do |f| %>
    <%= f.label :comment %>
    <%= f.text_field :content, class: 'form-control' %>
    <%= f.hidden_field :tour_id, value: @tour.id %>
    <%= f.hidden_field :category_id, value: Category.first.id %>
    <%= f.hidden_field :parent_id, value: comment.id %>
    <%= f.submit %>
  <% end %>
<% end %>

<%= link_to 'Back', tours_path %>