config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'addresses#index'
  post '/signup', to: 'users#create'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :tours
  resources :addresses
  resources :booking_requests
  resources :ratings
  resources :comments
  resources :categories
  resources :likes
  resources :activities

  namespace :admin do
    resources :tours
    resources :users
    resources :booking_requests
    resources :addresses
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
  has_one_attached :picture
  has_many :tours
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking_request.rb
class BookingRequest < ApplicationRecord
  belongs_to :tour
  belongs_to :user

  scope :waiting, ->{where(status: nil)}
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tour
  belongs_to :user
  has_many :likes
  belongs_to :category
  belongs_to :parent,  class_name: "Comment", optional: true 
  has_many   :sub_comments, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
  scope :root_comments, -> {where parent_id: nil}
  validates :content, presence: true, allow_blank: false
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :tour
  belongs_to :user
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_one_attached :picture
  belongs_to :address
  has_many :comments
  has_many :ratings
  has_many :booking_requests
  has_many :users, through: :booking_requests

  def self.search(name, page)
    if name	
      where('name LIKE ?', "%#{name}%").paginate(page: page)	
    else	
      paginate(page: page)	
    end	
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :booking_requests
  has_many :tours, through: :booking_requests
  has_many :comments
  has_many :likes
  has_many :liked_comments, through: :likes, source: :comment
  attr_accessor :remember_token
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, 
                    uniqueness: {case_sensitive: false}
  has_secure_password                                   
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? (remember_token)
  end
  def self.search(name, page)
    if name 
      where('name LIKE ?', "%#{name}%").paginate(page: page)  
    else  
      paginate(page: page)  
    end 
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new(like_params)
  end

  def create
    @like = current_user.likes.new(like_params)
    respond_to do |format|
      if @like.save
        format.html { redirect_to @like.comment.tour, notice: "like was successfully created." }
      else
        format.html { redirect_to @like.comment.tour, alert: @like.errors.full_messages.first}
      end
    end
  end

  def destroy
    @like = Like.find params[:id]
    comment = @like.comment
    respond_to do |format|
      if @like.destroy
        format.html { redirect_to comment.tour, notice: "unliked!"}
      end
    end
  end

  private
  def like_params
    params.require(:likes).permit(:user_id, :comment_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
      
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/user_helper.rb
module UserHelper
 def gravatar_for(user,options = {size: 80})
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size  = options[:size]
  gravatar_url  = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "booking tour travel", tours_path,  id: "logo"  %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users",  users_path  %></li>
          <li class="dropdown">
            <a  href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile",  current_user %></li>                          
              <li><%= link_to "Settings",edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log  out", logout_path,  method: "delete"%>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log  in",  login_path  %></li>
        <% end %>
       </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

<body>
  <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
        <% end %>
          <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>